/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.tecnocar.gui.cadastros;

import br.tecnocar.Util.Rotinas;
import br.tecnocar.main.Main;
import br.tecnocar.source.cadastros.Cidade;
import br.tecnocar.source.cadastros.Endereco;
import br.tecnocar.source.cadastros.Pessoa;
import br.tecnocar.util.Habilita_Desabilita_Campos;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MiltonRogerio
 */
public class CadCliente extends javax.swing.JDialog {

    Habilita_Desabilita_Campos hab_des = new Habilita_Desabilita_Campos();
    private Pessoa pessoa;
    private Endereco endereco;
    private int estado = Rotinas.PADRAO;
    private List<Cidade> listcidade;
    private Cidade cidade_ret;

    /**
     * Creates new form CadCliente
     */
    public CadCliente() {
    }

    public CadCliente(java.awt.Frame parent, boolean modal, Pessoa pessoa) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Cadastro de Cliente");
        this.pessoa = pessoa;
        atualizaCbCidade();
        jDcDtCadastro.setDate(new Date());
        hab_des.botaoCancelar(jPCadastro, jPBtn);
        jPDadosPessoais.setEnabled(false);
        jChkFisica.setSelected(true);
        preencherform();
    }

    private void preencherform() {
        if (pessoa == null) {
            pessoa = new Pessoa();
            endereco = new Endereco();
            return;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPCadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTfCodigo = new javax.swing.JTextField();
        jPPessoa = new javax.swing.JPanel();
        jChkFisica = new javax.swing.JCheckBox();
        jChkJuridica = new javax.swing.JCheckBox();
        jDcDtCadastro = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jPAtivo = new javax.swing.JPanel();
        jChkAtivo = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jTfNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTfFantasia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTfEndereco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTfNumero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTfCep = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTfBairro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTfComplemen = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jCbCidade = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jTfUF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTfCpfCnpj = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTfRgIe = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTfFone = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTfCel = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jCbOperadora = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jTfFax = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTfEmail = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTfObs = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jDcDtNascimento = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTVeiculos = new javax.swing.JTable();
        jPBtn = new javax.swing.JPanel();
        jBtnNovo = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnGravar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnIncluirVeic = new javax.swing.JButton();
        jBtnExcluiVeic = new javax.swing.JButton();
        jPDadosPessoais = new javax.swing.JPanel();
        jPDadosAdicionais = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jTfLocalTrabalho = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTfFoneDA = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTfTempTrab = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTfProfissao = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTfRenda = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTfNmConjuge = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTfConjuge = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTfCelConjuge = new javax.swing.JTextField();
        jPRefCome = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jTfEmpre1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTfFoneEmpre1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTfEmpre2 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTfFoneEmpre2 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jTfEmpre3 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jTfFoneEmpre3 = new javax.swing.JTextField();
        jPRefPessoais = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jTfRefPessoal1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTfFoneRefPessoal1 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jTfFoneRefPessoal2 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jTfRefPessoal3 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jTfFoneRefPessoal3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cliente");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Codigo");

        jTfCodigo.setEditable(false);
        jTfCodigo.setEnabled(false);

        jPPessoa.setBackground(new java.awt.Color(255, 255, 255));
        jPPessoa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pessoa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jChkFisica.setBackground(new java.awt.Color(255, 255, 255));
        jChkFisica.setText("Fisica");
        jChkFisica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkFisicaMouseClicked(evt);
            }
        });
        jChkFisica.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jChkFisicaFocusGained(evt);
            }
        });

        jChkJuridica.setBackground(new java.awt.Color(255, 255, 255));
        jChkJuridica.setText("Juridica");
        jChkJuridica.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jChkJuridicaFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPPessoaLayout = new javax.swing.GroupLayout(jPPessoa);
        jPPessoa.setLayout(jPPessoaLayout);
        jPPessoaLayout.setHorizontalGroup(
            jPPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPessoaLayout.createSequentialGroup()
                .addComponent(jChkFisica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jChkJuridica))
        );

        jPPessoaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jChkFisica, jChkJuridica});

        jPPessoaLayout.setVerticalGroup(
            jPPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jChkFisica)
                .addComponent(jChkJuridica))
        );

        jPPessoaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jChkFisica, jChkJuridica});

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Data Cadastro");

        jPAtivo.setBackground(new java.awt.Color(255, 255, 255));
        jPAtivo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ativo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jChkAtivo.setBackground(new java.awt.Color(255, 255, 255));
        jChkAtivo.setSelected(true);
        jChkAtivo.setText("Ativo");

        javax.swing.GroupLayout jPAtivoLayout = new javax.swing.GroupLayout(jPAtivo);
        jPAtivo.setLayout(jPAtivoLayout);
        jPAtivoLayout.setHorizontalGroup(
            jPAtivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAtivoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jChkAtivo)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPAtivoLayout.setVerticalGroup(
            jPAtivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAtivoLayout.createSequentialGroup()
                .addComponent(jChkAtivo)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Nome/Razao Social");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Fantasia");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Endereco");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Numero");

        jTfNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTfNumeroKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("CEP");

        jTfCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTfCepKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Bairro");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Complemento");

        jTfComplemen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfComplemenActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Cidade");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("UF");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("CPF/CNPJ");

        jTfCpfCnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTfCpfCnpjFocusLost(evt);
            }
        });
        jTfCpfCnpj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTfCpfCnpjKeyPressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("RG/IE");

        jTfRgIe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTfRgIeKeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Telefone");

        jTfFone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTfFoneKeyPressed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Celular");

        jTfCel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTfCelKeyPressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Operadora");

        jCbOperadora.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tim", "Vivo", "Claro", "Oi", " " }));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Fax");

        jTfFax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTfFaxKeyPressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("E-mail");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Observacao");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Data Nascimento");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Veiculos");

        jTVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Veiculo", "Placa", "Cor", "Ano", "Data Cadastro"
            }
        ));
        jScrollPane1.setViewportView(jTVeiculos);

        jBtnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/tecnocar/images/incluir.png"))); // NOI18N
        jBtnNovo.setText("NOVO");
        jBtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNovoActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/tecnocar/images/alterar.png"))); // NOI18N
        jBtnAlterar.setText("ALTERAR");

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/tecnocar/images/excluir.png"))); // NOI18N
        jBtnExcluir.setText("EXCLUIR");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/tecnocar/images/gravar.png"))); // NOI18N
        jBtnGravar.setText("GRAVAR");
        jBtnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGravarActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/tecnocar/images/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("CANCELAR");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPBtnLayout = new javax.swing.GroupLayout(jPBtn);
        jPBtn.setLayout(jPBtnLayout);
        jPBtnLayout.setHorizontalGroup(
            jPBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnGravar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPBtnLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtnAlterar, jBtnCancelar, jBtnExcluir, jBtnGravar, jBtnNovo});

        jPBtnLayout.setVerticalGroup(
            jPBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnNovo)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnGravar)
                    .addComponent(jBtnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPBtnLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtnAlterar, jBtnCancelar, jBtnExcluir, jBtnGravar, jBtnNovo});

        jBtnIncluirVeic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/tecnocar/images/incluir.png"))); // NOI18N
        jBtnIncluirVeic.setText("Incluir");

        jBtnExcluiVeic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/tecnocar/images/excluir.png"))); // NOI18N
        jBtnExcluiVeic.setText("Excluir");

        javax.swing.GroupLayout jPCadastroLayout = new javax.swing.GroupLayout(jPCadastro);
        jPCadastro.setLayout(jPCadastroLayout);
        jPCadastroLayout.setHorizontalGroup(
            jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPCadastroLayout.createSequentialGroup()
                            .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTfEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTfNome)
                                        .addGroup(jPCadastroLayout.createSequentialGroup()
                                            .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1)
                                                .addComponent(jTfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(29, 29, 29)
                                            .addComponent(jPPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPCadastroLayout.createSequentialGroup()
                                                    .addComponent(jLabel2)
                                                    .addGap(28, 28, 28))
                                                .addComponent(jDcDtCadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel3)))
                            .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPCadastroLayout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jPAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPCadastroLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jTfFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPCadastroLayout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel9))))
                                .addGroup(jPCadastroLayout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPCadastroLayout.createSequentialGroup()
                                            .addGap(241, 241, 241)
                                            .addComponent(jLabel11)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPCadastroLayout.createSequentialGroup()
                                            .addComponent(jTfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTfComplemen))))))
                        .addComponent(jLabel5)
                        .addGroup(jPCadastroLayout.createSequentialGroup()
                            .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPCadastroLayout.createSequentialGroup()
                                    .addComponent(jTfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPCadastroLayout.createSequentialGroup()
                                    .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jTfCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPCadastroLayout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(jLabel13)
                                            .addGap(82, 82, 82)
                                            .addComponent(jLabel14))
                                        .addGroup(jPCadastroLayout.createSequentialGroup()
                                            .addComponent(jTfRgIe, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel19)
                                                .addComponent(jTfFone, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(jPCadastroLayout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(jLabel7)
                                    .addGap(55, 55, 55)
                                    .addComponent(jLabel8)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPCadastroLayout.createSequentialGroup()
                                        .addComponent(jCbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTfUF))
                                    .addGroup(jPCadastroLayout.createSequentialGroup()
                                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPCadastroLayout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addGap(52, 52, 52)
                                                .addComponent(jLabel16))
                                            .addGroup(jPCadastroLayout.createSequentialGroup()
                                                .addComponent(jTfCel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jCbOperadora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jTfFax, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addComponent(jPBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPCadastroLayout.createSequentialGroup()
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPCadastroLayout.createSequentialGroup()
                                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPCadastroLayout.createSequentialGroup()
                                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPCadastroLayout.createSequentialGroup()
                                                .addComponent(jTfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTfObs))
                                            .addGroup(jPCadastroLayout.createSequentialGroup()
                                                .addGap(245, 245, 245)
                                                .addComponent(jLabel21)))
                                        .addGap(10, 10, 10))
                                    .addGroup(jPCadastroLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(462, 462, 462)))
                                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jDcDtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnIncluirVeic)
                            .addComponent(jBtnExcluiVeic))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPCadastroLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtnExcluiVeic, jBtnIncluirVeic});

        jPCadastroLayout.setVerticalGroup(
            jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(2, 2, 2)
                        .addComponent(jDcDtCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTfFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTfComplemen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPCadastroLayout.createSequentialGroup()
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTfUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTfCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTfRgIe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTfFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTfCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCbOperadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTfFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTfObs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jDcDtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPCadastroLayout.createSequentialGroup()
                        .addComponent(jBtnIncluirVeic)
                        .addGap(9, 9, 9)
                        .addComponent(jBtnExcluiVeic)))
                .addGap(18, 18, 18)
                .addComponent(jPBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPCadastroLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtnExcluiVeic, jBtnIncluirVeic});

        jTabbedPane1.addTab("Dados Principais", jPCadastro);

        jPDadosAdicionais.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jLabel22.setText("Local Trabalho.:");

        jLabel23.setText("Telefone:");

        jLabel24.setText("Tempo Trabalho:");

        jLabel25.setText("Profissao:");

        jLabel26.setText("Renda:");

        jLabel27.setText("Nome Conjuge..:");

        jLabel28.setText("Telefone:");

        jLabel29.setText("Celular:");

        javax.swing.GroupLayout jPDadosAdicionaisLayout = new javax.swing.GroupLayout(jPDadosAdicionais);
        jPDadosAdicionais.setLayout(jPDadosAdicionaisLayout);
        jPDadosAdicionaisLayout.setHorizontalGroup(
            jPDadosAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDadosAdicionaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDadosAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDadosAdicionaisLayout.createSequentialGroup()
                        .addGroup(jPDadosAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPDadosAdicionaisLayout.createSequentialGroup()
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTfLocalTrabalho))
                            .addGroup(jPDadosAdicionaisLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTfTempTrab, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTfProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPDadosAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addGroup(jPDadosAdicionaisLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPDadosAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTfFoneDA)
                                    .addComponent(jTfRenda, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPDadosAdicionaisLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfNmConjuge, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfConjuge, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfCelConjuge, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPDadosAdicionaisLayout.setVerticalGroup(
            jPDadosAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDadosAdicionaisLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPDadosAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTfLocalTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jTfFoneDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDadosAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTfTempTrab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jTfProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jTfRenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDadosAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jTfNmConjuge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(jTfConjuge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(jTfCelConjuge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        jPRefCome.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Referencias Comerciais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jLabel30.setText("Empresa:");

        jLabel31.setText("Telefone:");

        jLabel32.setText("Empresa:");

        jLabel33.setText("Telefone:");

        jLabel34.setText("Empresa:");

        jLabel35.setText("Telefone:");

        javax.swing.GroupLayout jPRefComeLayout = new javax.swing.GroupLayout(jPRefCome);
        jPRefCome.setLayout(jPRefComeLayout);
        jPRefComeLayout.setHorizontalGroup(
            jPRefComeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPRefComeLayout.createSequentialGroup()
                .addGroup(jPRefComeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPRefComeLayout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfEmpre3))
                    .addGroup(jPRefComeLayout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfEmpre2))
                    .addGroup(jPRefComeLayout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfEmpre1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPRefComeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPRefComeLayout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfFoneEmpre1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPRefComeLayout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfFoneEmpre2))
                    .addGroup(jPRefComeLayout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfFoneEmpre3))))
        );
        jPRefComeLayout.setVerticalGroup(
            jPRefComeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRefComeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPRefComeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPRefComeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTfEmpre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel31)
                        .addComponent(jTfFoneEmpre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel30))
                .addGroup(jPRefComeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPRefComeLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPRefComeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(jTfEmpre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPRefComeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel33)
                        .addComponent(jTfFoneEmpre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPRefComeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPRefComeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel34)
                        .addComponent(jTfEmpre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPRefComeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel35)
                        .addComponent(jTfFoneEmpre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPRefPessoais.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Referencias Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jLabel36.setText("Parentesco:");

        jLabel37.setText("Telefone:");

        jLabel38.setText("Parentesco:");

        jLabel39.setText("Telefone:");

        jLabel40.setText("Parentesco:");

        jLabel41.setText("Telefone:");

        javax.swing.GroupLayout jPRefPessoaisLayout = new javax.swing.GroupLayout(jPRefPessoais);
        jPRefPessoais.setLayout(jPRefPessoaisLayout);
        jPRefPessoaisLayout.setHorizontalGroup(
            jPRefPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRefPessoaisLayout.createSequentialGroup()
                .addGroup(jPRefPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPRefPessoaisLayout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfRefPessoal3))
                    .addGroup(jPRefPessoaisLayout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1))
                    .addGroup(jPRefPessoaisLayout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfRefPessoal1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPRefPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPRefPessoaisLayout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfFoneRefPessoal1))
                    .addGroup(jPRefPessoaisLayout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfFoneRefPessoal2))
                    .addGroup(jPRefPessoaisLayout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfFoneRefPessoal3))))
        );
        jPRefPessoaisLayout.setVerticalGroup(
            jPRefPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRefPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPRefPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPRefPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTfRefPessoal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel37)
                        .addComponent(jTfFoneRefPessoal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPRefPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addComponent(jTfFoneRefPessoal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPRefPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jTfRefPessoal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel41)
                    .addComponent(jTfFoneRefPessoal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPDadosPessoaisLayout = new javax.swing.GroupLayout(jPDadosPessoais);
        jPDadosPessoais.setLayout(jPDadosPessoaisLayout);
        jPDadosPessoaisLayout.setHorizontalGroup(
            jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPRefPessoais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPDadosAdicionais, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPRefCome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPDadosPessoaisLayout.setVerticalGroup(
            jPDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPDadosAdicionais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPRefCome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPRefPessoais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dados Adicionais", jPDadosPessoais);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jChkFisicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkFisicaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkFisicaMouseClicked

    private void jChkFisicaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jChkFisicaFocusGained
        // TODO add your handling code here:
        jChkJuridica.setSelected(false);
    }//GEN-LAST:event_jChkFisicaFocusGained

    private void jChkJuridicaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jChkJuridicaFocusGained
        // TODO add your handling code here:
        jChkFisica.setSelected(false);
    }//GEN-LAST:event_jChkJuridicaFocusGained

    private void jTfComplemenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfComplemenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfComplemenActionPerformed

    private void jBtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNovoActionPerformed
        // TODO add your handling code here:
        hab_des.botaoIncluir(jPCadastro, jPBtn);
        estado = Rotinas.INCLUINDO;
    }//GEN-LAST:event_jBtnNovoActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(null, "Deseja Cancelar este registro?", "Cancelar", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (resp == 0) {
            estado = Rotinas.PADRAO;
            hab_des.botaoCancelar(jPCadastro, jPBtn);
        }
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGravarActionPerformed
        // TODO add your handling code here:
        salvar();
    }//GEN-LAST:event_jBtnGravarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
//        excluir();
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jTfCpfCnpjKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfCpfCnpjKeyPressed
        // TODO add your handling code here:
        if (!Rotinas.somenteNumeros(jTfCpfCnpj.getText())) {
            JOptionPane.showMessageDialog(null, "Permitido digitar somente numero!");
            jTfCpfCnpj.setText("");
            jTfCpfCnpj.grabFocus();
        }
    }//GEN-LAST:event_jTfCpfCnpjKeyPressed

    private void jTfCepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfCepKeyPressed
        // TODO add your handling code here:
        if (!Rotinas.somenteNumeros(jTfCep.getText().toString())) {
            JOptionPane.showMessageDialog(null, "Permitido digitar somente numeros!");
            jTfCep.setText("");
            jTfCep.grabFocus();
        }

    }//GEN-LAST:event_jTfCepKeyPressed

    private void jTfNumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfNumeroKeyPressed
        // TODO add your handling code here:
        if (!Rotinas.somenteNumeros(jTfNumero.getText().toString())) {
            JOptionPane.showMessageDialog(null, "Permitido digitar somente numeros!");
            jTfNumero.setText("");
            jTfNumero.grabFocus();

        }
    }//GEN-LAST:event_jTfNumeroKeyPressed

    private void jTfRgIeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfRgIeKeyPressed
        // TODO add your handling code here:
        if (!Rotinas.somenteNumeros(jTfRgIe.getText().toString())) {
            JOptionPane.showMessageDialog(null, "Permitido digitar somente numeros!");
            jTfRgIe.setText("");
            jTfRgIe.grabFocus();
        }
    }//GEN-LAST:event_jTfRgIeKeyPressed

    private void jTfFoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfFoneKeyPressed
        // TODO add your handling code here:
        if (!Rotinas.somenteNumeros(jTfFone.getText().toString())) {
            JOptionPane.showMessageDialog(null, "Permitido digitar comente numeros!");
            jTfFone.setText("");
            jTfFone.grabFocus();
        }
    }//GEN-LAST:event_jTfFoneKeyPressed

    private void jTfCelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfCelKeyPressed
        // TODO add your handling code here:
        if (!Rotinas.somenteNumeros(jTfCel.getText().toString())) {
            JOptionPane.showMessageDialog(null, "Permitido digitar somente numeros!");
            jTfCel.setText("");
            jTfCel.grabFocus();
        }
    }//GEN-LAST:event_jTfCelKeyPressed

    private void jTfFaxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfFaxKeyPressed
        // TODO add your handling code here:
        if (!Rotinas.somenteNumeros(jTfFax.getText().toString())) {
            JOptionPane.showMessageDialog(null, "Permitido digitar somente numeros!");
            jTfFax.setText("");
            jTfFax.grabFocus();
        }
    }//GEN-LAST:event_jTfFaxKeyPressed

    private void jTfCpfCnpjFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTfCpfCnpjFocusLost
        // TODO add your handling code here:
        try {
            if (jChkFisica.isSelected()) {
                if (Rotinas.validaCpf(jTfCpfCnpj.getText().toString())) {
                    jTfCpfCnpj.setText(Rotinas.formatarString(jTfCpfCnpj.getText().toString(), "###.###.###-##"));
                } else {
                    JOptionPane.showMessageDialog(null, "CPF Invalido !");
                    jTfCpfCnpj.setText("");
                    jTfCpfCnpj.grabFocus();
                }
            } else {
                jTfCpfCnpj.setText(Rotinas.formatarString(jTfCpfCnpj.getText().toString(), "##.###.###/###-##"));
            }

        } catch (Exception err) {
            JOptionPane.showMessageDialog(null, err);
        }
    }//GEN-LAST:event_jTfCpfCnpjFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadCliente().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnExcluiVeic;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnGravar;
    private javax.swing.JButton jBtnIncluirVeic;
    private javax.swing.JButton jBtnNovo;
    private javax.swing.JComboBox jCbCidade;
    private javax.swing.JComboBox jCbOperadora;
    private javax.swing.JCheckBox jChkAtivo;
    private javax.swing.JCheckBox jChkFisica;
    private javax.swing.JCheckBox jChkJuridica;
    private com.toedter.calendar.JDateChooser jDcDtCadastro;
    private com.toedter.calendar.JDateChooser jDcDtNascimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPAtivo;
    private javax.swing.JPanel jPBtn;
    private javax.swing.JPanel jPCadastro;
    private javax.swing.JPanel jPDadosAdicionais;
    private javax.swing.JPanel jPDadosPessoais;
    private javax.swing.JPanel jPPessoa;
    private javax.swing.JPanel jPRefCome;
    private javax.swing.JPanel jPRefPessoais;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTVeiculos;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTfBairro;
    private javax.swing.JTextField jTfCel;
    private javax.swing.JTextField jTfCelConjuge;
    private javax.swing.JTextField jTfCep;
    private javax.swing.JTextField jTfCodigo;
    private javax.swing.JTextField jTfComplemen;
    private javax.swing.JTextField jTfConjuge;
    private javax.swing.JTextField jTfCpfCnpj;
    private javax.swing.JTextField jTfEmail;
    private javax.swing.JTextField jTfEmpre1;
    private javax.swing.JTextField jTfEmpre2;
    private javax.swing.JTextField jTfEmpre3;
    private javax.swing.JTextField jTfEndereco;
    private javax.swing.JTextField jTfFantasia;
    private javax.swing.JTextField jTfFax;
    private javax.swing.JTextField jTfFone;
    private javax.swing.JTextField jTfFoneDA;
    private javax.swing.JTextField jTfFoneEmpre1;
    private javax.swing.JTextField jTfFoneEmpre2;
    private javax.swing.JTextField jTfFoneEmpre3;
    private javax.swing.JTextField jTfFoneRefPessoal1;
    private javax.swing.JTextField jTfFoneRefPessoal2;
    private javax.swing.JTextField jTfFoneRefPessoal3;
    private javax.swing.JTextField jTfLocalTrabalho;
    private javax.swing.JTextField jTfNmConjuge;
    private javax.swing.JTextField jTfNome;
    private javax.swing.JTextField jTfNumero;
    private javax.swing.JTextField jTfObs;
    private javax.swing.JTextField jTfProfissao;
    private javax.swing.JTextField jTfRefPessoal1;
    private javax.swing.JTextField jTfRefPessoal3;
    private javax.swing.JTextField jTfRenda;
    private javax.swing.JTextField jTfRgIe;
    private javax.swing.JTextField jTfTempTrab;
    private javax.swing.JTextField jTfUF;
    // End of variables declaration//GEN-END:variables

    public void atualizaCbCidade() {
        listcidade = Main.dao.selecionaTodos(Cidade.class);

        for (Cidade cidade : listcidade) {
            jCbCidade.addItem(cidade.getNome());
        }
    }

    public void salvar() {

        if (jTfNome.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Nome/Razao Social e obrigatorio!");
            jTfNome.grabFocus();
        } else if (jTfEndereco.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Enderero e obrigatorio");
            jTfEndereco.grabFocus();
        } else if (jTfNumero.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, " Campo Numero e obrigatorio ");
            jTfNumero.grabFocus();
        } else if (jTfCpfCnpj.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo CPF/CNPJ obrigatorio");
            jTfCpfCnpj.grabFocus();
        } else {

            cidade_ret = (Cidade) Main.dao.selecionaNome(Cidade.class, jCbCidade.getSelectedItem().toString().toUpperCase());

            pessoa.setNome(jTfNome.getText());

            if (jChkFisica.isSelected()) {
                pessoa.setNomefantasia(jTfNome.getText());
            } else if (jChkJuridica.isSelected()) {
                pessoa.setNomefantasia(jTfComplemen.getText());
            }

            pessoa.setDtcadastro(jDcDtCadastro.getDate());
            pessoa.setDtnascimento(jDcDtNascimento.getDate());

            endereco.setLogradouro(jTfEndereco.getText());
            endereco.setNumero(Integer.parseInt(jTfNumero.getText()));
            endereco.setComplemento(jTfComplemen.getText());
            endereco.setCep(jTfCep.getText());
            endereco.setBairro(jTfBairro.getText());
            endereco.setCidade(cidade_ret);

            pessoa.setEndereco(endereco);

            if (jChkAtivo.isSelected()) {
                pessoa.setAtivo("S");
            } else {
                pessoa.setAtivo("N");
            }
            pessoa.setEmail(jTfEmail.getText());
            pessoa.setFone(jTfFone.getText());
            pessoa.setFonecel(jTfCel.getText());
            pessoa.setFonefax(jTfFax.getText());
            pessoa.setCpjcnpj(jTfCpfCnpj.getText());

            if (jChkFisica.isSelected()) {
                pessoa.setRg(jTfRgIe.getText());
            } else {

                pessoa.setIe(jTfRgIe.getText());
            }



            try {
                if (jTfCodigo.getText().isEmpty()) {
                    Main.dao.insere(pessoa);
                } else {
                    Main.dao.atualiza(pessoa);
                }
                dispose();
            } catch (Exception ex) {
                Logger.getLogger(CadCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        /*
         public void excluir() {
         if (estado == Rotinas.PESQUISANDO || !jTfCodigo.getText().equals("")) {
         if (Rotinas.confirma("Confirma exclusão do Modelo?") == JOptionPane.YES_NO_OPTION) {
         try {
         Main.dao.remove(pessoa);
         JOptionPane.showMessageDialog(null, "Excluído com Sucesso!");
         estado = Rotinas.PADRAO;
         hab_des.botaoCancelar(jPCadastro, jPBtn);
         } catch (Exception ex) {
         Logger.getLogger(CadModelo.class.getName()).log(Level.SEVERE, null, ex);
         }
         }
         } else {
         JOptionPane.showMessageDialog(null, "Faça uma pesquisa para poder excluir!");
         }
         }
         */
    }
}
