/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.tecnocar.gui.cadastros;

import br.tecnocar.Util.Rotinas;
import br.tecnocar.gui.consultas.jConsultaMarca;
import br.tecnocar.main.Main;
import br.tecnocar.source.cadastros.Marca;
import br.tecnocar.source.cadastros.Modelo;
import br.tecnocar.util.Habilita_Desabilita_Campos;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author MiltonRogerio
 */
public class CadModelo extends javax.swing.JDialog {

    Habilita_Desabilita_Campos hab_des = new Habilita_Desabilita_Campos();
    private Modelo modelo;
    private int estado = Rotinas.PADRAO;
    private Marca marca;

    public CadModelo() {
        initComponents();
        preencherform();
    }

    public CadModelo(java.awt.Frame parent, boolean modal, Modelo modelo) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.modelo = modelo;
        hab_des.botaoCancelar(jPCadastro, jPBtn);
        preencherform();
    }

    private void preencherform() {
        if (modelo == null) {
            modelo = new Modelo();
            return;
        }

        hab_des.botaoIncluir(jPCadastro, jPBtn);
        jTfCodigo.setText(modelo.getId().toString());
        jTfNome.setText(modelo.getNome());
        jTfCodigoMarca.setText(modelo.getMarca().getId().toString());
        jTfNomeMarca.setText(modelo.getMarca().getNome());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPCadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTfCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTfCodigoMarca = new javax.swing.JTextField();
        jBtnPesqMarca = new javax.swing.JButton();
        jTfNomeMarca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTfNome = new javax.swing.JTextField();
        jPBtn = new javax.swing.JPanel();
        jBtnNovo = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnGravar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro Modelo Veiculo");

        jLabel2.setText("Codigo");

        jTfCodigo.setEditable(false);
        jTfCodigo.setEnabled(false);

        jLabel3.setText("Descricao");

        jLabel4.setText("Codigo");

        jTfCodigoMarca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTfCodigoMarcaFocusLost(evt);
            }
        });

        jBtnPesqMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/tecnocar/images/viewmag.png"))); // NOI18N
        jBtnPesqMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesqMarcaActionPerformed(evt);
            }
        });

        jLabel5.setText("Descricao Marca");

        jBtnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/tecnocar/images/incluir.png"))); // NOI18N
        jBtnNovo.setText("NOVO");
        jBtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNovoActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/tecnocar/images/alterar.png"))); // NOI18N
        jBtnAlterar.setText("ALTERAR");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/tecnocar/images/excluir.png"))); // NOI18N
        jBtnExcluir.setText("EXCLUIR");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/tecnocar/images/gravar.png"))); // NOI18N
        jBtnGravar.setText("GRAVAR");
        jBtnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGravarActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/tecnocar/images/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("CANCELAR");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPBtnLayout = new javax.swing.GroupLayout(jPBtn);
        jPBtn.setLayout(jPBtnLayout);
        jPBtnLayout.setHorizontalGroup(
            jPBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBtnLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jBtnNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnExcluir)
                .addGap(10, 10, 10)
                .addComponent(jBtnGravar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPBtnLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtnAlterar, jBtnCancelar, jBtnExcluir, jBtnGravar, jBtnNovo});

        jPBtnLayout.setVerticalGroup(
            jPBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBtnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnGravar)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnNovo))
                .addGap(35, 35, 35))
        );

        jPBtnLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtnAlterar, jBtnCancelar, jBtnExcluir, jBtnGravar, jBtnNovo});

        javax.swing.GroupLayout jPCadastroLayout = new javax.swing.GroupLayout(jPCadastro);
        jPCadastro.setLayout(jPCadastroLayout);
        jPCadastroLayout.setHorizontalGroup(
            jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPCadastroLayout.createSequentialGroup()
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTfCodigoMarca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                            .addComponent(jTfCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTfNome)
                            .addComponent(jLabel3)
                            .addGroup(jPCadastroLayout.createSequentialGroup()
                                .addComponent(jBtnPesqMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jTfNomeMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(176, 176, 176))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCadastroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPCadastroLayout.setVerticalGroup(
            jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCadastroLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTfCodigoMarca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnPesqMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTfNomeMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jPBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNovoActionPerformed
        // TODO add your handling code here:
        hab_des.botaoIncluir(jPCadastro, jPBtn);
        estado = Rotinas.INCLUINDO;
    }//GEN-LAST:event_jBtnNovoActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(null, "Deseja Cancelar este registro?", "Cancelar", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (resp == 0) {
            estado = Rotinas.PADRAO;
            hab_des.botaoCancelar(jPCadastro, jPBtn);
        }
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        excluir();
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jBtnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGravarActionPerformed
        // TODO add your handling code here:
        salvar();
    }//GEN-LAST:event_jBtnGravarActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        salvar();
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jTfCodigoMarcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTfCodigoMarcaFocusLost
        // TODO add your handling code here:
        marca = (Marca) Main.dao.buscaID(Marca.class, jTfCodigoMarca.getText());
        if (marca == null && !jTfCodigoMarca.getText().trim().equals("")) {
            //JOptionPane.sohow
            JOptionPane.showMessageDialog(null, "Nao encontrou a marca digitada!");
            jTfCodigoMarca.setText("");
            jTfNomeMarca.setText("");
            jTfCodigoMarca.grabFocus();
        } else {
            jTfNomeMarca.setText(marca.getNome());
        }
    }//GEN-LAST:event_jTfCodigoMarcaFocusLost

    private void jBtnPesqMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesqMarcaActionPerformed
        // TODO add your handling code here:
//        new jConsultaMarca(true).setVisible(true);
        JFrame mainFrame = new JFrame();
        final jConsultaMarca jcm = new jConsultaMarca(mainFrame, true);
        jcm.setVisible(true);
        jcm.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent evt) {
                jTfCodigoMarca.setText(jcm.id_Retorno);
                jTfNomeMarca.setText(jcm.nome_Retorno);
            }
        });
    }//GEN-LAST:event_jBtnPesqMarcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadModelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadModelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadModelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadModelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadModelo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnGravar;
    private javax.swing.JButton jBtnNovo;
    private javax.swing.JButton jBtnPesqMarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPBtn;
    private javax.swing.JPanel jPCadastro;
    private javax.swing.JTextField jTfCodigo;
    private javax.swing.JTextField jTfCodigoMarca;
    private javax.swing.JTextField jTfNome;
    private javax.swing.JTextField jTfNomeMarca;
    // End of variables declaration//GEN-END:variables

    public void salvar() {

        if (jTfNome.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Nome Descricao e obrigatorio!");
            jTfNome.grabFocus();
        } else if (jTfNomeMarca.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo Descricao Marca e obrigatorio");
        } else {
            modelo.setNome(jTfNome.getText());
            marca = (Marca) Main.dao.buscaID(Marca.class, jTfCodigoMarca.getText());
            modelo.setMarca(marca);
            try {
                if (jTfCodigo.getText().isEmpty()) {
                    Main.dao.insere(modelo);
                } else {
                    Main.dao.atualiza(modelo);
                }
                dispose();
            } catch (Exception ex) {
                Logger.getLogger(CadModelo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void excluir() {
        if (estado == Rotinas.PESQUISANDO || !jTfCodigo.getText().equals("")) {
            if (Rotinas.confirma("Confirma exclusão do Modelo?") == JOptionPane.YES_NO_OPTION) {
                try {
                    Main.dao.remove(modelo);
                    JOptionPane.showMessageDialog(null, "Excluído com Sucesso!");
                    estado = Rotinas.PADRAO;
                    hab_des.botaoCancelar(jPCadastro, jPBtn);
                } catch (Exception ex) {
                    Logger.getLogger(CadModelo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Faça uma pesquisa para poder excluir!");
        }
    }
}
